# Generated by Django 4.0.4 on 2022-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
