# Generated by Django 4.1.4 on 2023-01-23 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partner_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='address_line_3',
        ),
        migrations.AddField(
            model_name='inventory',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='city_town',
            field=models.TextField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='province_region_state',
            field=models.TextField(default='State', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='zip_code',
            field=models.IntegerField(default=105031, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line_1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line_2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
