# Generated by Django 4.1.4 on 2023-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_inventory', '0002_remove_partner_address_line_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city_town',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='province_region_state',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
