# Generated by Django 4.1.4 on 2023-01-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_inventory', '0003_alter_partner_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
