# Generated by Django 4.0.4 on 2022-08-07 09:03

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('partner_inventory', '0003_alter_user_dob_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> origin/API_TEST
