# Generated by Django 3.2.17 on 2023-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_inventory', '0004_alter_partner_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image_url',
            field=models.TextField(default='NA', max_length=2500),
        ),
    ]
